[package]
name = "wrencher"
version = "0.1.0"
edition = "2021"

[dependencies]
ruint = "1.12.3"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
